server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This is important for Angular routing
        # If a file isn't found, serve index.html so Angular handles the route
        try_files $uri $uri/ /index.html;
    }
}
